"""Communication protocol for agent-to-agent messaging and action planning."""

import re
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass


@dataclass
class CommunicationMessage:
    """Structured communication message between agents."""
    from_agent: str
    to_agent: str
    message: str
    timestamp: int = 0


@dataclass
class ActionPlan:
    """Structured action plan generated by LLM."""
    action: str  # e.g., "cook_dish", "pickup_ingredient", "deliver_dish", "wait"
    ingredients: Optional[List[int]] = None  # For cook_dish or pickup_ingredient
    target_location: Optional[Tuple[int, int]] = None  # For location-based actions
    description: Optional[str] = None  # Human-readable description


@dataclass
class LLMResponse:
    """Parsed LLM response containing communication and plan."""
    communication: Optional[CommunicationMessage] = None
    plan: Optional[ActionPlan] = None
    raw_response: str = ""


SYSTEM_PROMPT = """You are an agent in a cooperative cooking game called Overcooked. You work with another agent to cook dishes and deliver them to the goal.

Your task:
1. Observe your local environment
2. Communicate with the other agent about your plans and needs
3. Generate an action plan for what you will do next

Available actions:
- cook_dish: Cook a dish in a pot with specific ingredients
- pickup_ingredient: Pick up an ingredient from a pile
- pickup_plate: Pick up a plate from a plate pile
- deliver_dish: Deliver a completed dish to the goal
- wait: Wait for the other agent or for cooking to complete
- move_to: Move to a specific location

Respond in the following XML format:
<communication>
  <to_agent>agent_X</to_agent>
  <message>Your message to the other agent</message>
</communication>
<plan>
  <action>action_name</action>
  <ingredients>[ingredient0, ingredient1, ingredient2]</ingredients>
  <target_location>(x, y)</target_location>
  <description>Human-readable description of your plan</description>
</plan>"""


def format_agent_prompt(
    obs_text: str,
    agent_id: int,
    conversation_history: List[CommunicationMessage],
    other_agent_id: int = None,
) -> List[Dict[str, str]]:
    """Format prompt for a single agent with their observation and conversation history.
    
    Args:
        obs_text: Text description of agent's observation
        agent_id: Current agent's ID (0 or 1)
        conversation_history: List of previous messages between agents
        other_agent_id: Other agent's ID (defaults to 1 - agent_id)
        
    Returns:
        List of message dicts in chat format for LLM
    """
    if other_agent_id is None:
        other_agent_id = 1 - agent_id
    
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT}
    ]
    
    # Add conversation history
    if conversation_history:
        history_text = "Conversation History:\n"
        for msg in conversation_history[-5:]:  # Last 5 messages
            history_text += f"[{msg.from_agent} to {msg.to_agent}]: {msg.message}\n"
        messages.append({"role": "user", "content": history_text})
    
    # Add current observation
    obs_prompt = f"""You are agent_{agent_id}. The other agent is agent_{other_agent_id}.

Your Observation:
{obs_text}

Generate your communication message to agent_{other_agent_id} and your action plan:"""
    
    messages.append({"role": "user", "content": obs_prompt})
    
    return messages


def parse_llm_response(response: str, from_agent: str, to_agent: str) -> LLMResponse:
    """Parse LLM response to extract communication and plan.
    
    Args:
        response: Raw LLM response text
        from_agent: Agent ID generating this response
        to_agent: Target agent ID for communication
        
    Returns:
        LLMResponse object with parsed communication and plan
    """
    result = LLMResponse(raw_response=response)
    
    # Extract communication
    comm_match = re.search(
        r'<communication>.*?<to_agent>(.*?)</to_agent>.*?<message>(.*?)</message>.*?</communication>',
        response,
        re.DOTALL
    )
    
    if comm_match:
        to_agent_parsed = comm_match.group(1).strip()
        message = comm_match.group(2).strip()
        result.communication = CommunicationMessage(
            from_agent=from_agent,
            to_agent=to_agent_parsed,
            message=message
        )
    
    # Extract plan
    plan_match = re.search(
        r'<plan>.*?<action>(.*?)</action>.*?</plan>',
        response,
        re.DOTALL
    )
    
    if plan_match:
        action = plan_match.group(1).strip()
        
        # Extract optional fields
        ingredients_match = re.search(r'<ingredients>(.*?)</ingredients>', response, re.DOTALL)
        location_match = re.search(r'<target_location>\((.*?)\)</target_location>', response, re.DOTALL)
        desc_match = re.search(r'<description>(.*?)</description>', response, re.DOTALL)
        
        ingredients = None
        if ingredients_match:
            ing_str = ingredients_match.group(1).strip()
            # Parse list format [0, 1, 2]
            ing_list_match = re.search(r'\[(.*?)\]', ing_str)
            if ing_list_match:
                try:
                    ingredients = [int(x.strip()) for x in ing_list_match.group(1).split(',')]
                except ValueError:
                    pass
        
        target_location = None
        if location_match:
            loc_str = location_match.group(1).strip()
            try:
                x, y = loc_str.split(',')
                target_location = (int(x.strip()), int(y.strip()))
            except ValueError:
                pass
        
        description = desc_match.group(1).strip() if desc_match else None
        
        result.plan = ActionPlan(
            action=action,
            ingredients=ingredients,
            target_location=target_location,
            description=description
        )
    
    return result


def update_conversation_history(
    history: List[CommunicationMessage],
    message: CommunicationMessage,
    max_history: int = 20,
) -> List[CommunicationMessage]:
    """Update conversation history with new message.
    
    Args:
        history: Current conversation history
        message: New message to add
        max_history: Maximum number of messages to keep
        
    Returns:
        Updated conversation history
    """
    new_history = history + [message]
    return new_history[-max_history:]


def format_conversation_history_for_display(
    history: List[CommunicationMessage],
) -> str:
    """Format conversation history as readable text.
    
    Args:
        history: List of messages
        
    Returns:
        Formatted string
    """
    if not history:
        return "No previous messages."
    
    lines = []
    for msg in history:
        lines.append(f"[{msg.from_agent} → {msg.to_agent}]: {msg.message}")
    
    return "\n".join(lines)


def validate_plan(plan: ActionPlan, env, agent_pos: Tuple[int, int]) -> Tuple[bool, str]:
    """Validate that a plan is executable in the current environment.
    
    Args:
        plan: Action plan to validate
        env: OvercookedV2 environment
        agent_pos: Current agent position
        
    Returns:
        Tuple of (is_valid, error_message)
    """
    if plan is None:
        return False, "No plan provided"
    
    valid_actions = [
        "cook_dish", "pickup_ingredient", "pickup_plate",
        "deliver_dish", "wait", "move_to"
    ]
    
    if plan.action not in valid_actions:
        return False, f"Invalid action: {plan.action}"
    
    # Validate action-specific requirements
    if plan.action == "cook_dish":
        if plan.ingredients is None or len(plan.ingredients) != 3:
            return False, "cook_dish requires exactly 3 ingredients"
        if plan.target_location is None:
            return False, "cook_dish requires target_location (pot position)"
    
    if plan.action == "pickup_ingredient":
        if plan.ingredients is None or len(plan.ingredients) == 0:
            return False, "pickup_ingredient requires at least one ingredient"
        if plan.target_location is None:
            return False, "pickup_ingredient requires target_location (pile position)"
    
    if plan.action == "move_to":
        if plan.target_location is None:
            return False, "move_to requires target_location"
    
    # Check if target location is within bounds
    if plan.target_location:
        x, y = plan.target_location
        if x < 0 or x >= env.width or y < 0 or y >= env.height:
            return False, f"Target location ({x}, {y}) is out of bounds"
    
    return True, ""

