"""Rich display utilities for agent context visualization."""

from typing import List, Dict, Tuple, Optional
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.console import Group
from rich.text import Text
from rich.markup import escape

from .communication import LLMResponse, ActionPlan, get_plan_warnings

console = Console()


def display_agent_context(
    agent_id: int,
    step: int,
    obs_text: str,
    prompt: List[Dict[str, str]],
    raw_response: str,
    parsed_response: LLMResponse,
    plan: Optional[ActionPlan],
    validation_result: Tuple[bool, str],
    executor_actions: List[int],
    executor_info: Dict,
    previous_validation_errors: List[str],
    env,
) -> None:
    """Display agent context using rich.
    
    Args:
        agent_id: Agent ID (0 or 1)
        step: Current step number
        obs_text: Text observation of the agent
        prompt: Full prompt sent to LLM
        raw_response: Raw LLM response string
        parsed_response: Parsed LLM response
        plan: Action plan (may be None if invalid)
        validation_result: Tuple of (is_valid, error_msg)
        executor_actions: List of action indices generated by executor
        executor_info: Dictionary with executor information
        previous_validation_errors: List of validation errors from previous step
        env: Environment instance (for warnings)
    """
    # Create main panel
    title = f"Agent {agent_id} - Step {step}"
    content_parts = []
    
    # Observation - escape markup to prevent parsing errors
    content_parts.append(Panel(
        escape(obs_text),
        title="[bold cyan]Observation[/bold cyan]",
        border_style="cyan"
    ))
    
    # Previous validation errors - escape markup
    if previous_validation_errors:
        error_text = "\n".join([f"⚠️ {escape(err)}" for err in previous_validation_errors])
        content_parts.append(Panel(
            error_text,
            title="[bold yellow]Previous Validation Errors[/bold yellow]",
            border_style="yellow"
        ))
    
    # Prompt - escape content to prevent markup parsing
    prompt_text = "\n\n".join([
        f"[bold]{msg['role']}[/bold]:\n{escape(msg['content'])}"
        for msg in prompt
    ])
    content_parts.append(Panel(
        prompt_text,
        title="[bold blue]Prompt to LLM[/bold blue]",
        border_style="blue"
    ))
    
    # Raw LLM Response - escape markup to prevent parsing errors
    content_parts.append(Panel(
        escape(raw_response),
        title="[bold green]Raw LLM Response[/bold green]",
        border_style="green"
    ))
    
    # Parsed Response
    parsed_info = []
    parse_errors = []
    
    # Check communication parsing - escape user content
    if parsed_response.communication:
        parsed_info.append(f"[bold green]✓ Communication parsed[/bold green]")
        parsed_info.append(f"  Message: {escape(str(parsed_response.communication.message))}")
        parsed_info.append(f"  To: {escape(str(parsed_response.communication.to_agent))}")
    else:
        parse_errors.append("[yellow]⚠️ No communication parsed from response[/yellow]")
    
    # Check plan parsing - escape user content
    if parsed_response.plan:
        parsed_info.append(f"[bold green]✓ Plan parsed[/bold green]")
        parsed_info.append(f"  Action: {escape(str(parsed_response.plan.action))}")
        if parsed_response.plan.description:
            parsed_info.append(f"  Description: {escape(str(parsed_response.plan.description))}")
        if parsed_response.plan.ingredients:
            parsed_info.append(f"  Ingredients: {escape(str(parsed_response.plan.ingredients))}")
        else:
            parsed_info.append(f"  [yellow]⚠️ No ingredients specified[/yellow]")
        if parsed_response.plan.target_location:
            parsed_info.append(f"  Target Location: {escape(str(parsed_response.plan.target_location))}")
        else:
            parsed_info.append(f"  [yellow]⚠️ No target location specified[/yellow]")
    else:
        parse_errors.append("[yellow]⚠️ No plan parsed from response[/yellow]")
        # Try to detect why parsing failed
        if "<plan>" not in raw_response and "</plan>" not in raw_response:
            parse_errors.append("  [dim]Reason: No <plan> tags found in response[/dim]")
        elif "<action>" not in raw_response:
            parse_errors.append("  [dim]Reason: No <action> tag found in <plan>[/dim]")
    
    if parse_errors:
        parsed_info.extend(parse_errors)
    
    content_parts.append(Panel(
        "\n".join(parsed_info) if parsed_info else "[yellow]No information parsed[/yellow]",
        title="[bold magenta]Parsed Response[/bold magenta]",
        border_style="magenta"
    ))
    
    # Validation - escape error messages
    is_valid, error_msg = validation_result
    if is_valid:
        validation_text = "[bold green]✓ Plan is valid[/bold green]"
    else:
        validation_text = f"[bold red]✗ Plan validation failed:[/bold red]\n{escape(str(error_msg))}"
    
    warnings = get_plan_warnings(plan, env) if plan else []
    if warnings:
        escaped_warnings = [escape(str(w)) for w in warnings]
        validation_text += f"\n[yellow]Warnings:[/yellow] {', '.join(escaped_warnings)}"
    
    content_parts.append(Panel(
        validation_text,
        title="[bold yellow]Validation[/bold yellow]",
        border_style="yellow"
    ))
    
    # Executor Info
    executor_text = []
    action_names = {0: "right", 1: "down", 2: "left", 3: "up", 4: "stay", 5: "interact"}
    
    if executor_info.get("error"):
        executor_text.append(f"[bold red]✗ Executor Error:[/bold red] {escape(str(executor_info['error']))}")
    elif executor_info.get("using_buffer"):
        executor_text.append(f"[bold]Using action buffer[/bold]")
        executor_text.append(f"  Buffer length: {executor_info.get('buffer_length', 0)}")
        if executor_actions:
            action_name = action_names.get(executor_actions[0], "unknown")
            executor_text.append(f"  Next action: {action_name} ({executor_actions[0]})")
    else:
        if executor_actions:
            executor_text.append(f"[bold green]✓ Action sequence generated[/bold green]")
            executor_text.append(f"  Count: {len(executor_actions)}")
            action_names_list = [action_names.get(a, f"unknown({a})") for a in executor_actions[:5]]
            executor_text.append(f"  Actions: {', '.join(action_names_list)}" + 
                                (f" ... ({len(executor_actions)} total)" if len(executor_actions) > 5 else ""))
        else:
            executor_text.append(f"[bold red]✗ No actions generated[/bold red]")
            executor_text.append(f"  [dim]Executor returned empty sequence[/dim]")
        
        if executor_info.get("plan_action"):
            executor_text.append(f"  Plan: {escape(str(executor_info['plan_action']))}")
        if executor_info.get("target_found") is not None:
            target_status = "✓ Found" if executor_info['target_found'] else "✗ Not found"
            executor_text.append(f"  Target: {target_status}")
    
    content_parts.append(Panel(
        "\n".join(executor_text) if executor_text else "[yellow]No executor info[/yellow]",
        title="[bold cyan]Executor Result[/bold cyan]",
        border_style="cyan"
    ))
    
    # Display - use Group to combine multiple panels
    console.print(Panel(
        Group(*content_parts),
        title=f"[bold white]{title}[/bold white]",
        border_style="white"
    ))


def display_step_summary(
    step: int,
    actions: Dict[str, int],
    rewards: Dict[str, float],
    total_reward: float,
    plan_status: Optional[Dict[str, bool]] = None,
    llm_responses: Optional[Dict[str, any]] = None,
) -> None:
    """Display step summary table.
    
    Args:
        step: Step number
        actions: Dictionary of actions for each agent
        rewards: Dictionary of rewards for each agent (from environment)
        total_reward: Total episode reward so far
        plan_status: Optional dictionary with plan validation and execution status
        llm_responses: Optional dictionary with LLM responses (to check if plan was parsed)
    """
    action_names = {0: "right", 1: "down", 2: "left", 3: "up", 4: "stay", 5: "interact"}
    summary_table = Table(title=f"Step {step} Summary", show_header=True, header_style="bold magenta")
    summary_table.add_column("Agent", style="cyan")
    summary_table.add_column("Action", style="green")
    summary_table.add_column("Env Reward", style="yellow")
    summary_table.add_column("Plan Reward", style="green")
    summary_table.add_column("Total Step", style="blue")
    summary_table.add_column("Episode Total", style="magenta")
    
    for agent_key, action_idx in actions.items():
        agent_id = int(agent_key.split("_")[1])
        action_name = action_names.get(action_idx, "unknown")
        
        # Environment reward
        env_reward = rewards.get(agent_key, 0.0)
        
        # Compute plan-based rewards
        plan_reward = 0.0
        if plan_status and llm_responses:
            agent_id_str = f"agent_{agent_id}"
            plan_valid_key = f"plan_valid_{agent_id_str}"
            is_valid = plan_status.get(plan_valid_key, False)
            
            # Plan parsing reward (only if plan is also valid)
            if llm_responses.get(agent_id_str) and llm_responses[agent_id_str].plan and is_valid:
                plan_reward += 0.1
            
            # Plan validation reward
            if is_valid:
                plan_reward += 0.3
            
            # Plan execution reward
            plan_executed_key = f"plan_executed_{agent_id_str}"
            if plan_status.get(plan_executed_key, False):
                plan_reward += 0.5
        
        total_step_reward = env_reward + plan_reward
        
        summary_table.add_row(
            f"Agent {agent_id}",
            action_name,
            f"{env_reward:.2f}",
            f"{plan_reward:.2f}",
            f"{total_step_reward:.2f}",
            f"{total_reward:.2f}"
        )
    
    console.print(summary_table)

